#!/usr/bin/env sh

set -eu

HERE=$(dirname "$0")
REPO_BASE_DIR=$(
  cd "${HERE}"
  unset GIT_DIR
  git rev-parse --show-toplevel
)

cd "${REPO_BASE_DIR}/python"
export PATH="${REPO_BASE_DIR}/python/.venv/bin:$PATH"

pytest -m slow

set +eu
